Add global kafka.enabled config item
micronaut-projects/micronaut-kafka pull request #211
Opened 2020-08-18 09:18 UTC by mitchjust-finocomp

@graemerocher I'm trying to resolve #138, allowing consumers and streams to be disabled is relatively straight forward, but producers were a bit tougher, as they're created adhoc by the intro advice - any ideas on how this could be done better?

2020-08-18 09:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-kafka?pullRequest=211) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-kafka?pullRequest=211) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-kafka?pullRequest=211) it.</sub>

2020-08-19 20:43 UTC, marcosflobo commented
Thank you for your work on this feature request!

2020-08-20 09:22 UTC, alvarosanchez requested changes
Is it your intention to create no-op implementations so that existing code doesn't blow up when Kafka is disabled?

2020-08-20 09:22 UTC, alvarosanchez commented on kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/KafkaStreamsFactory.java
> +@Requires(property = AbstractKafkaConfiguration.PREFIX + "." + AbstractKafkaConfiguration.ENABLED_CONFIG, value = "true", defaultValue = "true")
Wouldn't this be better?

```suggestion
@Requires(property = AbstractKafkaConfiguration.PREFIX + "." + AbstractKafkaConfiguration.ENABLED_CONFIG, value = "true", defaultValue = AbstractKafkaConfiguration.DEFAULT_ENABLED)
```

2020-08-20 09:22 UTC, alvarosanchez commented on kafka/src/main/java/io/micronaut/configuration/kafka/intercept/KafkaClientIntroductionAdvice.java
> +                LOG.debug("Kafka is disabled, skipping producer configuration...");
We usually wrap logging calls in `if (LOG.isXXXEnabled){}`

2020-08-20 09:22 UTC, alvarosanchez commented on kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
> +@Requires(property = AbstractKafkaConfiguration.PREFIX + "." + AbstractKafkaConfiguration.ENABLED_CONFIG, value = "true", defaultValue = "true")
```suggestion
@Requires(property = AbstractKafkaConfiguration.PREFIX + "." + AbstractKafkaConfiguration.ENABLED_CONFIG, value = "true", defaultValue = AbstractKafkaConfiguration.DEFAULT_ENABLED)
```

2020-08-20 09:22 UTC, alvarosanchez commented on kafka/src/main/java/io/micronaut/configuration/kafka/NoopProducer.java
> +/*
Why is this needed? Is it so that `@KafkaClient`s don't fail when Kafka is disabled?

2020-08-20 09:22 UTC, alvarosanchez commented on kafka/src/main/java/io/micronaut/configuration/kafka/NoopProducer.java
> +public class NoopProducer implements Producer {
Needs author and since tags

2020-08-20 10:01 UTC, mitchjust-finocomp commented
> Is it your intention to create no-op implementations so that existing code doesn't blow up when Kafka is disabled?

@alvarosanchez that was the plan - I'm not particularly happy with that impl, would it be preferable to have `@KafkaClient`s throw an exception when kafka is disabled and you attempt to publish?

2020-08-20 10:55 UTC, alvarosanchez commented
@mitchjust-finocomp so @graemerocher and I have been discussing about this, and we are not keen on adding no-op implementations.

We believe that Kafka should be disabled globally adding the `@Requires` condition at the `package-info.java` level. Then, it is the user's responsibility to provide `@Fallback` implementations for those `@KafkaClient`s if they intend to disable Kafka.

2020-08-25 20:57 UTC, marcosflobo commented
@alvarosanchez is that the common strategy for the rest of "connectors" like this Kafka?

2020-10-14 21:48 UTC, marcosflobo commented
Is there anything I could do to help here?

2021-02-17 16:27 UTC, eutkin commented
Hi all, any progress?

2021-03-02 01:49 UTC, mitchjust-finocomp commented
New PR: https://github.com/micronaut-projects/micronaut-kafka/pull/334

2021-03-02 01:49 UTC, closed without merging