Metrics Tags Updates
micronaut-projects/micronaut-kafka pull request #226
Opened 2020-08-26 17:58 UTC by brianwyka

- Add `topic` as an included tag for metrics by default.
- Add `@Override` for consumer metrics to also include `group-id` tag

2020-08-27 08:20 UTC, graemerocher requested changes

2020-08-27 08:20 UTC, graemerocher commented on gradle.properties
> +projectVersion=2.2.0
Please roll back this change

2020-08-27 13:05 UTC, brianwyka commented on gradle.properties
> +projectVersion=2.2.0
@graemerocher, rolled back.

2020-08-27 13:58 UTC, graemerocher commented
Needs a test as well

2020-08-31 13:43 UTC, brianwyka commented
> Needs a test as well

@graemerocher, happy to add some tests.  Is there a spec I can update, or will this be a new test?  Didn't see anything in there already.

2020-09-10 09:34 UTC, alvarosanchez commented
If you didn't see any fit, just create a new spec.

2020-09-10 14:35 UTC, ctoestreich commented
@brianwyka The tests I wrote to hit the metrics endpoint for the kafka metrics could be useful here as you can hit the endpoint and check the tags in the response?  You shoud be able to marry together a test container spec and then after messages are sent and received check the metrics endpoint for metrics tags?

2020-11-10 19:53 UTC, brianwyka commented
I will be revisiting this to add tests today and tomorrow @alvarosanchez

2020-11-10 22:56 UTC, brianwyka commented
Attempting to make a change in kafka clients as well:
https://github.com/apache/kafka/pull/9584

2021-01-21 16:41 UTC, closed without merging