Add KafkaPartition and KafkaPartitionKey annotations
micronaut-projects/micronaut-kafka pull request #387
Opened 2021-06-19 20:43 UTC by bugflux

Hi all,

Although I haven't faced this need in micronaut projects yet, I have found if potentially useful to control partitioning separately from record keys.

This is useful when Keys have specific functional requirement (deduplication, log compaction, etc), but where partition of a topic needs to be made on a separate field (often having a one to many relationship with record keys, although that's not a requirement).

This PR brings in the ability to do just that with two new additional annotations: `@KafkaPartition` and `@KafkaPartitionKey`.

2021-06-19 20:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-kafka?pullRequest=387) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-kafka?pullRequest=387) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-kafka?pullRequest=387) it.</sub>

2021-06-19 21:07 UTC, bugflux commented on kafka/src/main/java/io/micronaut/configuration/kafka/annotation/KafkaPartition.java
> + * will not throw an exception, the outcome of doing so is left unspecified.</p>
I'm not sure if this is good behaviour. I'm happy to implement a different one with some advice/guidance

2021-06-30 10:50 UTC, graemerocher approved these changes

2021-06-30 10:50 UTC, graemerocher commented
Thanks for the contribution, this looks good

2021-06-30 10:52 UTC, graemerocher commented
Could you address the compilation errors?

2021-06-30 10:53 UTC, graemerocher requested changes
Resolve compilation errors please.

2021-07-01 07:00 UTC, bugflux commented
I believe I fixed the Java 8 compilation issue. I'm not entirely sure whether GraalVM's build will be fixed though, I'm not sure why it failed

2021-07-01 11:58 UTC, bugflux commented
Looks like one test is flaky, perhaps some concurrency issue and/or misuse of index-based access to queues, but I'm not sure since I don't have a strong grasp of the language. I'll look more into it but any input would be appreciated.

2021-07-01 12:31 UTC, graemerocher commented
yeah getting async tests right can be challenging it might be best to wait first until the size of the collection is what you expect and then do any index based queries

2021-07-02 06:46 UTC, bugflux commented
It was fairly obvious, actually. Should be good now. I appreciate the patience :-)

2021-07-05 06:35 UTC, merged

2021-07-05 06:35 UTC, graemerocher commented
Thanks for the contribution!