GH-227 adds all tags available from kafka metrics
micronaut-projects/micronaut-kafka pull request #513
Opened 2022-03-22 15:00 UTC by timyates

Merges master in to https://github.com/micronaut-projects/micronaut-kafka/pull/410

Checked with JAPICMP and all looks good (the change is binary compatible)

![image](https://user-images.githubusercontent.com/49317/159512356-7f3144cb-896e-48c0-8821-828eedde6670.png)

2022-03-22 15:07 UTC, sdelamo requested changes

2022-03-22 15:07 UTC, sdelamo commented on kafka/src/main/java/io/micronaut/configuration/kafka/metrics/ConsumerKafkaMetricsReporter.java
> +        tags.add("partition");
extract-constant

2022-03-22 15:07 UTC, sdelamo commented on kafka/src/main/java/io/micronaut/configuration/kafka/metrics/AbstractKafkaMetricsReporter.java
> +        tags.add("client-id");
extract constants

2022-03-22 15:15 UTC, timyates commented
@sdelamo done, and updated japicmp image above

2022-03-22 18:24 UTC, timyates commented
@dstepanov Hiya! 👋 I noticed you recently made changes in the tests that are failing...  Do you have an idea about how to fix the flakiness?

2022-03-23 10:39 UTC, timyates commented
Asked a question as to why we are not seeing a metric used in the tests

https://github.com/micronaut-projects/micronaut-kafka/pull/410#pullrequestreview-918549554

2022-03-23 17:56 UTC, timyates commented on kafka/src/test/groovy/io/micronaut/configuration/kafka/AbstractEmbeddedServerSpec.groovy
> -
This shouldn't be required as they're already marked with `@AutoCleanup`

2022-03-23 18:18 UTC, timyates commented
@sdelamo All green 😅  ready for review

2022-11-16 07:29 UTC, merged