Introduce `KafkaListener.threadsValue` to allow for dynamic config
micronaut-projects/micronaut-kafka pull request #769
Opened 2023-07-12 08:31 UTC by guillermocalvo

Closes #689

2023-07-13 11:51 UTC, jeremyg484 approved these changes
Looks good, though it is a breaking change as noted.

If we don't want to force another major version bump for something this simple, an alternate approach would be to keep the existing attribute as an `int` and add an alternate attribute to the annotation that is a `String`.

@sdelamo What do you think?

2023-07-19 11:00 UTC, sdelamo submitted a review, later dismissed
we cannot do a breaking change now. Too late. either we search for a workaround or we do it for the next major version of Micronaut Kafka

2023-07-19 11:05 UTC, dstepanov commented
I would keep it as an int and introduce `threadsValue`

2023-07-19 15:24 UTC, jeremyg484 requested changes

2023-07-19 15:24 UTC, jeremyg484 commented on kafka/src/test/groovy/io/micronaut/configuration/kafka/annotation/KafkaListenerSpec.groovy
> +    @KafkaListener(clientId = "kafka-consumer-with-configurable-number-of-threads", threadsValue = '${my.thread.count}')
I'd like to see some additional test cases to also exercise setting the `threads` attribute, and then setting both `threadsValue` and `threads` at the same time.

2023-07-19 18:39 UTC, jeremyg484 approved these changes

2023-07-26 08:33 UTC, dstepanov approved these changes

2023-08-04 07:29 UTC, sdelamo approved these changes

2023-08-04 07:29 UTC, merged