Update guide ("Embedding Kafka" -> "Dockerizing Kafka")
micronaut-projects/micronaut-kafka pull request #777
Opened 2023-07-14 08:55 UTC by guillermocalvo

Closes #435

2023-07-17 07:53 UTC, sdelamo commented on src/main/docs/guide/toc.yml
> +  kafkaDockerized: Dockerizing Kafka
```suggestion
  kafkaDockerized: Running Kafka while testing and developing
```

2023-07-17 10:28 UTC, guillermocalvo commented on src/main/docs/guide/kafkaClient/kafkaDockerized.adoc
> +The previous section introduced the ability to use a Kafka docker container. This is possible by using
@sdelamo I added a new test under `tasks-sasl-plaintext` because all the other subprojects use Groovy+Spock.

2023-07-17 11:31 UTC, sdelamo requested changes
Create a 

- `test-suite`
- `test-suite-groovy`
- `test-suite-kotlin` 


structure and use the snippet macro. 

See https://github.com/micronaut-projects/micronaut-microstream build for an example.

2023-07-19 10:55 UTC, sdelamo approved these changes

2023-07-19 15:31 UTC, sdelamo commented
@guillermocalvo Ci never ends. any idea?

2023-07-19 15:52 UTC, guillermocalvo commented
> @guillermocalvo Ci never ends. any idea?

I'll take a look at it.

2023-07-20 12:59 UTC, merged