Multi-language documentation for Injecting Kafka Producer Beans example
micronaut-projects/micronaut-kafka pull request #826
Opened 2023-08-18 17:16 UTC by wetted

2023-08-18 17:26 UTC, wetted commented
@timyates thanks for helping

2023-08-21 06:29 UTC, sdelamo commented on test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/producer/inject/Book.groovy
> +    Book(String title) {
remove constructor. Annotate `Book` with `@Canonical` or use `new Book(title: "foo")`

2023-08-21 14:46 UTC, sdelamo approved these changes

2023-08-21 15:25 UTC, timyates commented on test-suite/src/test/java/io/micronaut/kafka/docs/producer/inject/BookSenderTest.java
> +        bookSender.send("Stephen King", book);
```suggestion

        try (ApplicationContext ctx = ApplicationContext.run( // <1>
            Map.of("kafka.enabled", "true", "spec.name", "BookSenderTest")
        )) {
            BookSender bookSender = ctx.getBean(BookSender.class); // <2>
            Book book = new Book("The Stand");
            bookSender.send("Stephen King", book);
        }
```

2023-08-21 15:29 UTC, timyates commented on test-suite/src/test/java/io/micronaut/kafka/docs/producer/inject/BookSenderTest.java
> +        bookSender.send("Stephen King", book);
Sonar also points out that this doesn't have any assertions

2023-08-21 16:13 UTC, timyates requested changes
The tests should assert something 😎

2023-08-21 16:48 UTC, timyates approved these changes

2023-08-21 17:21 UTC, merged