Multi-language documentation for Forwarding Messages with @SendTo example
micronaut-projects/micronaut-kafka pull request #827
Opened 2023-08-18 19:32 UTC by wetted

2023-08-18 19:34 UTC, wetted commented
This could probably use some tests, although these docs examples never had any to begin with.

2023-08-21 06:25 UTC, sdelamo requested changes
Please, add tests

2023-08-21 06:25 UTC, sdelamo commented on test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/sendto/ProductListener.groovy
> +@KafkaListener
It misses `@Requires(property = "spec.name"` to avoid bean pollution.

2023-08-21 06:25 UTC, sdelamo commented on test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/sendto/ProductListener.kt
> +@KafkaListener
It misses `@Requires(property = "spec.name"` to avoid bean pollution.

2023-08-21 06:25 UTC, sdelamo commented on test-suite-groovy/src/test/groovy/io/micronaut/kafka/docs/consumer/sendto/WordCounter.groovy
> +@KafkaListener(
It misses `@Requires(property = "spec.name"` to avoid bean pollution.

2023-08-21 06:25 UTC, sdelamo commented on test-suite-kotlin/src/test/kotlin/io/micronaut/kafka/docs/consumer/sendto/WordCounter.kt
> +@KafkaListener(
It misses `@Requires(property = "spec.name"` to avoid bean pollution.

2023-08-21 06:25 UTC, sdelamo commented on test-suite/src/test/java/io/micronaut/kafka/docs/consumer/sendto/WordCounter.java
> +@KafkaListener(
It misses `@Requires(property = "spec.name"` to avoid bean pollution.

2023-08-21 06:25 UTC, sdelamo commented on test-suite/src/test/java/io/micronaut/kafka/docs/consumer/sendto/ProductListener.java
>  @KafkaListener
It misses `@Requires(property = "spec.name"` to avoid bean pollution.

2023-08-22 10:23 UTC, sdelamo reviewed
is this PR ready for review?

2023-08-22 12:56 UTC, wetted commented
> is this PR ready for review?

no, still meeds tests

2023-08-28 11:14 UTC, guillermocalvo requested changes

2023-08-28 13:45 UTC, guillermocalvo approved these changes

2023-08-28 14:58 UTC, merged