Multi-language docs examples for Kafka Streams
micronaut-projects/micronaut-kafka pull request #839
Opened 2023-08-23 21:08 UTC by wetted

2023-08-25 08:59 UTC, guillermocalvo commented on src/main/docs/guide/kafkaStreams.adoc
> +snippet::io.micronaut.kafka.docs.streams.WordCountStream[tags="clazz, myOtherStream"]
```suggestion
snippet::io.micronaut.kafka.docs.streams.WordCountStream[tags="myOtherStream"]
```

Unless you have a specific reason in mind to make this snippet longer than it was, I would leave out `clazz` to keep it similar to the original example:

```java
@Named("my-other-stream")
KStream<String, String> myOtherKStream(@Named("my-other-stream") ConfiguredStreamBuilder builder)  {...}
```

2023-08-25 08:59 UTC, guillermocalvo commented on src/main/docs/guide/kafkaStreams.adoc
> +snippet::io.micronaut.kafka.docs.streams.WordCountStream[tags="clazz, namedStream"]
Same here:

```suggestion
snippet::io.micronaut.kafka.docs.streams.WordCountStream[tags="namedStream"]
```

2023-08-25 09:00 UTC, guillermocalvo commented
LGTM 👍

2023-08-28 14:21 UTC, sdelamo commented
> LGTM 👍

@guillermocalvo Please, use the GitHub review PR functionality to signal whether you approve, reject or leave comments in a PR.

2023-08-28 14:26 UTC, sdelamo approved these changes

2023-08-28 14:42 UTC, guillermocalvo commented
> @guillermocalvo Please, use the GitHub review PR functionality to signal whether you approve, reject or leave comments in a PR.

@sdelamo I left a comment because at the time the PR was not ready for review yet. Do you guys usually approve/reject draft PRs? I can do that next time.

2023-08-28 14:55 UTC, sdelamo commented
> > @guillermocalvo Please, use the GitHub review PR functionality to signal whether you approve, reject or leave comments in a PR.
> 
> @sdelamo I left a comment because at the time the PR was not ready for review yet. Do you guys usually approve/reject draft PRs? I can do that next time.

no, we don't review Draft PRs generally.

2023-08-28 14:59 UTC, guillermocalvo commented
> no, we don't review Draft PRs generally.

That's what I thought, which is why I left a comment in the draft PR to indicate that it looked good to me so far.

2023-08-28 15:01 UTC, guillermocalvo requested changes
`WordCountStreamTest` is satisfied if `client.publishSentence()` doesn't throw any exceptions; I don't believe that's proof enough that the Kafka stream is doing its job, is it?

I'm also missing `WordCountStreamTest` for `test-suite-groovy` and `test-suite-groovy`.

2023-08-29 12:17 UTC, guillermocalvo approved these changes

2023-08-29 12:52 UTC, merged