Add option to customise close() wait (fixes #901)
micronaut-projects/micronaut-kafka pull request #902
Opened 2023-10-24 17:17 UTC by agarciadom

This pull request proposes a new option to customise how long we wait for each `KafkaStreams` to close, as a fix for #901.

If you have a better idea for the name of the option, please let me know. I was not sure whether to go with `kafka.streams.close-seconds` or `kafka.streams-close-seconds`.

2023-10-24 17:18 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-kafka?pullRequest=902) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-kafka?pullRequest=902) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-kafka?pullRequest=902) it.</sub>

2023-11-09 10:04 UTC, sdelamo requested changes

2023-11-09 10:04 UTC, sdelamo commented on kafka-streams/src/main/java/io/micronaut/configuration/kafka/streams/KafkaStreamsFactory.java
> +    @Value("${kafka.streams-close-seconds:3}")
this should be in in a `@ConfigurationProperties` object with the default value there.

2023-11-09 10:04 UTC, sdelamo commented
@jeremyg484 please, follow-up this PR from @agarciadom

2024-01-22 23:25 UTC, jeremyg484 commented
@agarciadom Thanks for your initial work on this. I've gone ahead and picked up the PR and done the configuration in a bit more of a typical Micronaut way using `@ConfigurationProperties` as Sergio had suggested above. If you get a chance to try these updates out to ensure it satisfies your use case that would be great!

2024-01-23 10:04 UTC, agarciadom commented
Thank you for the changes! Apologies for not being able to do it myself: I was busy with my teaching and I wasn't entirely sure about how to follow the suggested approach.

I'll give this a go :-).

2024-01-23 12:02 UTC, agarciadom commented
I can confirm that with the PR, I can replace my manual workaround with this addition to my `application-test.yml` file:

```yaml
kafka:
  streams:
    default:
      close-timeout: 60s
```

I'm not sure why it takes so long to shutdown after my last test (that's for another discussion, I guess!), but at least it does get the tests to pass.

Thank you for your work!

2024-01-23 14:29 UTC, jeremyg484 commented
> I can confirm that with the PR, I can replace my manual workaround with this addition to my `application-test.yml` file:
> 
> ```yaml
> kafka:
>   streams:
>     default:
>       close-timeout: 60s
> ```
> 
> I'm not sure why it takes so long to shutdown after my last test (that's for another discussion, I guess!), but at least it does get the tests to pass.
> 
> Thank you for your work!

Great, glad it's working for you!

I've been seeing the same issue with it taking a long time to shutdown the streams sometimes in our tests. As far as I can tell, it's something purely on the Kafka side of things and not anything we're doing wrong in the module. It is something I intend to dig into separately though as it's making running the whole streams test suite quite sluggish.

2024-03-07 00:53 UTC, jeremyg484 approved these changes

2024-03-07 16:05 UTC, merged