Support for ConsumerRecords container type on batch processing
micronaut-projects/micronaut-kafka pull request #904
Opened 2023-10-26 13:22 UTC by rorueda

See #903

The changes are:
- Bind arguments of `ConsumerRecords` type;
- Consider `ConsumerRecords` type when looking for the "body argument" to configure the correct key and value deserializers;
- Add a test;

2023-11-12 21:27 UTC, sdelamo commented
@jeremyg484 can you please review this?

2023-11-13 15:38 UTC, jeremyg484 requested changes
The idea and code itself are great, other than my minor nitpicking about not using `Optional` as a method parameter.

Beyond that, the docs need to be updated to describe this new option.

2023-11-13 15:38 UTC, jeremyg484 commented on kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
> +    private void configureKeyDeserializer(Optional<Argument<?>> bodyArgument, ExecutableMethod<?, ?> method, DefaultKafkaConsumerConfiguration config) {
We generally try not to use `Optional` as a method parameter (though I know there are some cases in this project where that has been violated).

Can you refactor this to use the previous signature without `Optional`?

2023-11-13 15:38 UTC, jeremyg484 commented on kafka/src/main/java/io/micronaut/configuration/kafka/processor/KafkaConsumerProcessor.java
> +    private void configureValueDeserializer(Optional<Argument<?>> bodyArgument, DefaultKafkaConsumerConfiguration config) {
We generally try not to use `Optional` as a method parameter (though I know there are some cases in this project where that has been violated).

Can you refactor this to use the previous signature without `Optional`?

2023-11-13 22:23 UTC, rorueda commented
I rebased it onto master and made the requested change.

2024-01-12 22:21 UTC, merged